version: '3.8'

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secret}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      TZ: ${TZ:-Asia/Tokyo}
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    command: -c 'config_file=/etc/postgresql/postgresql.conf'
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./Docker/postgres/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./Docker/postgres/log:/log
      - ./schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
volumes:
  pgdata:
